import { useState } from "react";
import { useNavigate } from "react-router-dom";
import styles from "./LaundryRooms.module.css";
import FixedHeader from "../FixedHeader";

const CATEGORIES = [
  {
    icon: "🧺",
    name: "Washing Machine",
    tagline: "The most neglected appliance",
    tips: [
      {
        title: "Run a hot maintenance wash monthly",
        text: "A washing machine that is never cleaned accumulates detergent residue, mould spores, and bacteria in the drum, door seal, and detergent drawer. Once a month, run the machine on its hottest cycle (90°C or the dedicated drum-clean setting) with either a specialist washing machine cleaner or 200ml of white vinegar in the drum. Nothing in the drum — no clothes, no detergent. This eliminates odour-causing bacteria and prevents the musty smell that transfers to clothes.",
      },
      {
        title: "Wipe the door seal after every wash",
        text: "The rubber door gasket on front-loading machines is the primary site for mould growth in a laundry room. Water and lint collect in its folds after every wash and, if not wiped dry, begin growing mould within 24–48 hours. Pull back the seal and wipe it with a dry cloth after each cycle, and leave the door open between washes to allow the drum to dry out completely.",
      },
      {
        title: "Clean the detergent drawer weekly",
        text: "Detergent residue builds up in the dispenser drawer within days, becoming a sticky paste that blocks water flow and reduces wash effectiveness. Remove the drawer completely (it slides out on most machines), rinse under hot water, scrub all compartments with an old toothbrush, and leave to dry before replacing. Clean the cavity behind it with a damp cloth.",
      },
      {
        title: "Check and clean the filter quarterly",
        text: "Most front-loading washing machines have a filter at the bottom front behind a small panel. This filter collects lint, coins, and debris and, if blocked, reduces pump efficiency and drainage speed. Unscrew it with a cloth ready for water spillage, remove all debris, rinse under running water, and replace. Do this every three months or whenever drainage seems slow.",
      },
      {
        title: "Don't use too much detergent",
        text: "Excess detergent does not make clothes cleaner — it leaves residue in the machine that builds up into mould-friendly deposits over time. Modern concentrated detergents require far less than the fill-line on the cap suggests. Use the manufacturer-recommended amount for your water hardness and load size, and reduce by 20–30% if you notice a persistent musty smell or excessive suds.",
      },
    ],
  },
  {
    icon: "🌀",
    name: "Dryer",
    tagline: "Clean it or it's a fire risk",
    tips: [
      {
        title: "Clean the lint filter after every single cycle",
        text: "A clogged lint filter is not just a cleaning issue — it is a fire hazard. Lint is highly combustible and the heat generated by a dryer is more than sufficient to ignite it. Clean the lint filter after every cycle without exception. It takes 10 seconds. This is the most important maintenance task for any dryer and the one most frequently skipped.",
      },
      {
        title: "Inspect and clean the exhaust vent annually",
        text: "Lint that passes through the filter accumulates in the exhaust duct over time. A partially or fully blocked vent significantly increases drying time, increases energy consumption, and — critically — creates a fire risk. Once a year, disconnect the vent duct and clean it thoroughly with a long brush or vacuum attachment. Check the external vent flap opens and closes freely.",
      },
      {
        title: "Wipe the drum interior monthly",
        text: "Residue from fabric softener sheets, dye from clothes, and moisture from damp items leave a film inside the dryer drum that transfers to clean laundry. Wipe the interior drum with a damp cloth monthly and run a 10-minute cycle on low heat with a clean, dry towel to absorb any moisture before the next load.",
      },
      {
        title: "Leave the dryer door open between uses",
        text: "Like the washing machine, a dryer that is kept closed between uses traps residual moisture inside the drum. Even a few degrees of heat retention combined with trapped humidity encourages musty odours. Leave the door ajar between cycles to allow air circulation and moisture to escape.",
      },
    ],
  },
  {
    icon: "🪣",
    name: "Surfaces & Sink",
    tagline: "The forgotten areas",
    tips: [
      {
        title: "Descale the laundry sink weekly",
        text: "If your laundry room has a utility sink, limescale and detergent residue accumulate rapidly around the basin, taps, and plug. Spray with undiluted white vinegar, leave for 10 minutes, and wipe clean with a cloth. For stubborn limescale around taps, wrap a vinegar-soaked cloth around them and leave for 30 minutes before wiping.",
      },
      {
        title: "Wipe shelves and surfaces monthly",
        text: "Shelves holding detergents, fabric softeners, and laundry products accumulate drips and spills that dry into a sticky residue. Wipe all laundry room shelving monthly with a damp cloth, moving all products to clean behind and underneath them. Pay particular attention to the area directly under frequently used dispensers.",
      },
      {
        title: "Sweep and mop the floor weekly",
        text: "Laundry room floors collect lint, detergent powder, and water constantly. Lint in particular accumulates rapidly and, if left, can become damp and harbour bacteria. Sweep the floor weekly and mop with a diluted floor cleaner. Pay attention to the area directly around and behind the appliances where lint and fluff accumulate invisibly.",
      },
      {
        title: "Clean behind appliances at least twice a year",
        text: "The area behind the washing machine and dryer is one of the most neglected spaces in any home. Lint, dust, and occasionally small items accumulate there and are invisible until you pull the appliances out. Move the appliances forward twice a year, vacuum and mop behind them, check the hoses for kinks or leaks, and replace the appliances carefully.",
      },
    ],
  },
  {
    icon: "💧",
    name: "Prevent Mould",
    tagline: "Humidity is the enemy",
    tips: [
      {
        title: "Ventilate the laundry room continuously",
        text: "Washing and drying generates more airborne moisture than almost any other household activity. Without ventilation, this moisture condenses on walls, windows, and behind appliances, creating conditions for mould growth within days. Keep a window open when machines are running, use an extractor fan if one is fitted, and leave the room door open to encourage air circulation after cycles complete.",
      },
      {
        title: "Never leave wet clothes in the machine",
        text: "Wet clothes left in a washing machine drum for more than two hours begin developing musty odours as bacteria multiply rapidly in the warm, moist environment. These odours can be very difficult to remove even with a re-wash. Transfer clothes to the dryer or drying rack immediately after the cycle ends. If you forget, re-run on a rinse cycle before drying.",
      },
      {
        title: "Treat any mould immediately",
        text: "Mould in a laundry room spreads faster than in almost any other room because of the persistent humidity. If you spot mould on walls, ceiling, grout, or behind appliances, treat it immediately with a specialist mould remover — not just bleach, which discolours without killing the root. After treatment, identify and address the moisture source: inadequate ventilation, a leaking hose, or a dryer vent that exhausts inside rather than outside.",
      },
      {
        title: "Use a dehumidifier if there is no external ventilation",
        text: "In laundry rooms without an external window or extractor fan, a portable dehumidifier running during wash and dry cycles dramatically reduces the airborne moisture that causes mould, condensation, and odours. Empty the water reservoir after each use and clean the filter monthly. A dehumidifier in a sealed laundry room reduces mould risk more effectively than any cleaning product.",
      },
    ],
  },
];

const MAINTENANCE_TASKS = [
  { task: "Wipe door seal", freq: "After every wash", icon: "🫧" },
  { task: "Clean lint filter", freq: "After every dry", icon: "🌀" },
  { task: "Leave doors open", freq: "Between every use", icon: "🚪" },
  { task: "Clean detergent drawer", freq: "Weekly", icon: "🧼" },
  { task: "Sweep laundry floor", freq: "Weekly", icon: "🧹" },
  { task: "Descale sink", freq: "Weekly", icon: "💧" },
  { task: "Maintenance wash (machine)", freq: "Monthly", icon: "🔁" },
  { task: "Wipe dryer drum", freq: "Monthly", icon: "🌀" },
  { task: "Wipe shelves and surfaces", freq: "Monthly", icon: "🧽" },
  { task: "Clean washing machine filter", freq: "Quarterly", icon: "🔧" },
  { task: "Clean dryer exhaust vent", freq: "Annually", icon: "💨" },
  { task: "Clean behind appliances", freq: "Twice a year", icon: "📦" },
];

const FREQ_COLORS = {
  "After every wash": "rgb(187, 19, 47)",
  "After every dry": "rgb(187, 19, 47)",
  "Between every use": "rgb(187, 19, 47)",
  Weekly: "rgb(32, 32, 65)",
  Monthly: "rgb(100, 80, 0)",
  Quarterly: "rgb(20, 100, 60)",
  Annually: "rgb(80, 20, 100)",
  "Twice a year": "rgb(20, 80, 100)",
};

const FREQ_BG = {
  "After every wash": "rgb(255, 235, 238)",
  "After every dry": "rgb(255, 235, 238)",
  "Between every use": "rgb(255, 235, 238)",
  Weekly: "rgb(235, 235, 255)",
  Monthly: "rgb(255, 243, 205)",
  Quarterly: "rgb(220, 245, 230)",
  Annually: "rgb(240, 220, 255)",
  "Twice a year": "rgb(220, 240, 255)",
};

const TIPS = [
  "The most important laundry room habit costs nothing and takes 10 seconds — leave the washing machine door open after every cycle. This single action prevents the majority of drum mould.",
  "Buy less detergent, not more. Excess detergent is the primary cause of washing machine odour build-up and reduces the need for frequent maintenance washes.",
  "Set a recurring monthly phone reminder for your washing machine maintenance wash — it is the only laundry room task that is genuinely easy to forget and has significant consequences when skipped.",
  "If your laundry room smells persistently musty despite cleaning, the source is almost certainly the washing machine door seal or the exhaust vent — these are the two areas that trap moisture most effectively.",
  "Never dry clothes indoors in the laundry room without ventilation — a single load of washing releases litres of moisture into the air, which condenses on every cold surface in the room.",
];

const FAQS = [
  {
    q: "Why does my washing machine smell even when clean?",
    a: "The most common cause is mould in the door seal. Pull back the rubber gasket and inspect the inside folds — black or grey spotting indicates mould growth. Clean with a specialist mould remover, run a 90°C maintenance wash, and from then on wipe the seal dry after every wash and leave the door open between uses. If the smell persists, clean the detergent drawer and its cavity, and check the filter.",
  },
  {
    q: "How do I remove detergent residue from the drum?",
    a: "Run the machine empty on the hottest cycle with 200ml of white vinegar in the drum and 2 tablespoons of baking soda in the detergent drawer. The combination breaks down detergent and softener residue effectively. For severe build-up, a commercial washing machine cleaner used according to the manufacturer's instructions will be more effective than vinegar alone.",
  },
  {
    q: "My dryer takes much longer than it used to — what's wrong?",
    a: "The most likely cause is a partially blocked lint filter or exhaust vent duct. Clean the lint filter thoroughly — not just the surface — by rinsing under water and allowing to dry fully. Then disconnect the exhaust duct and inspect for lint accumulation. A significantly blocked duct almost always explains a sudden increase in drying time and represents a fire risk that should be addressed immediately.",
  },
  {
    q: "How do I stop mould growing on the laundry room walls?",
    a: "Mould on laundry room walls is caused by condensation from inadequate ventilation. The immediate fix is to treat existing mould with a specialist remover and repaint with anti-mould paint. The permanent fix is to improve ventilation — an extractor fan that runs automatically when the room is in use, or a dehumidifier if an external vent is not possible. Addressing the moisture source is the only lasting solution.",
  },
  {
    q: "How often should I clean my washing machine?",
    a: "A maintenance wash should be run monthly, the detergent drawer cleaned weekly, the door seal wiped after every wash, and the filter checked quarterly. This schedule prevents build-up rather than addressing it after it develops. A machine on this routine should never develop significant odour or require an emergency deep clean.",
  },
  {
    q: "Can I use bleach to clean my washing machine?",
    a: "Bleach can be used for the drum on machines that explicitly permit it (check your manual), but it damages rubber seals over time with repeated use. White vinegar or a purpose-made washing machine cleaner is safer for regular maintenance. For the door seal, use a specialist mould remover rather than bleach, which discolours mould without killing the underlying spores.",
  },
];

export default function LaundryRooms() {
  const navigate = useNavigate();
  const [activeCategory, setActiveCategory] = useState("Washing Machine");
  const [openTip, setOpenTip] = useState(null);
  const [openFaq, setOpenFaq] = useState(null);

  const category = CATEGORIES.find((c) => c.name === activeCategory);

  return (
    <div className={styles.page}>
      <FixedHeader />

      {/* Hero */}
      <div className={styles.hero}>
        <p className={styles.heroEyebrow}>Laundry room cleaning guide</p>
        <h1 className={styles.heroTitle}>
          A laundry room that
          <br />
          <em>actually stays clean.</em>
        </h1>
        <p className={styles.heroDesc}>
          Practical tips for cleaning and maintaining your washing machine,
          dryer, surfaces, and laundry room — including the tasks most people
          skip until it's too late.
        </p>
        <div className={styles.heroDivider} />
        <div className={styles.heroButtons}>
          <button
            className={styles.heroPrimary}
            onClick={() => navigate("/maids")}
          >
            Book a Professional
          </button>
          <button
            className={styles.heroSecondary}
            onClick={() =>
              document
                .getElementById("tips-section")
                .scrollIntoView({ behavior: "smooth" })
            }
          >
            Read the Tips
          </button>
        </div>
      </div>

      {/* Trust bar */}
      <div className={styles.trustBar}>
        {[
          ["🧺", "Appliance-specific tips"],
          ["🔥", "Fire safety included"],
          ["💧", "Mould prevention"],
          ["📋", "Full maintenance schedule"],
          ["✅", "Expert-approved"],
        ].map(([emoji, text]) => (
          <div key={text} className={styles.trustItem}>
            <span className={styles.trustEmoji}>{emoji}</span>
            <span className={styles.trustText}>{text}</span>
          </div>
        ))}
      </div>

      {/* Category tips */}
      <div className={styles.section} id="tips-section">
        <p className={styles.sectionEyebrow}>Area-by-area tips</p>
        <h2 className={styles.sectionTitle}>
          Everything your laundry room needs
        </h2>
        <p className={styles.sectionDesc}>
          Select a category to read the tips. Each section covers a different
          part of your laundry room — appliances, surfaces, and mould
          prevention.
        </p>

        {/* Category tabs */}
        <div className={styles.catTabs}>
          {CATEGORIES.map((c) => (
            <button
              key={c.name}
              className={`${styles.catTab} ${activeCategory === c.name ? styles.catTabActive : ""}`}
              onClick={() => {
                setActiveCategory(c.name);
                setOpenTip(null);
              }}
            >
              <span className={styles.catTabIcon}>{c.icon}</span>
              <span>{c.name}</span>
            </button>
          ))}
        </div>

        {/* Active category label */}
        <div className={styles.catLabel}>
          <span className={styles.catLabelIcon}>{category.icon}</span>
          <div>
            <p className={styles.catLabelName}>{category.name}</p>
            <p className={styles.catLabelTagline}>{category.tagline}</p>
          </div>
        </div>

        {/* Tips accordion */}
        <div className={styles.tipsList}>
          {category.tips.map((tip, i) => (
            <div
              key={tip.title}
              className={`${styles.tipCard} ${openTip === i ? styles.tipCardOpen : ""}`}
            >
              <button
                className={styles.tipQuestion}
                onClick={() => setOpenTip(openTip === i ? null : i)}
              >
                <div className={styles.tipQuestionLeft}>
                  <div className={styles.tipNum}>{i + 1}</div>
                  <span className={styles.tipTitle}>{tip.title}</span>
                </div>
                <span
                  className={`${styles.tipChevron} ${openTip === i ? styles.tipChevronOpen : ""}`}
                >
                  ▾
                </span>
              </button>
              {openTip === i && <p className={styles.tipAnswer}>{tip.text}</p>}
            </div>
          ))}
        </div>
      </div>

      {/* Maintenance schedule */}
      <div className={styles.schedule}>
        <p
          className={styles.sectionEyebrow}
          style={{ color: "rgba(255,255,255,0.6)" }}
        >
          Complete maintenance schedule
        </p>
        <h2 className={styles.scheduleTitle}>
          Every task and how often to do it
        </h2>
        <p className={styles.scheduleSub}>
          Every laundry room maintenance task in one place, colour-coded by
          frequency. Use this to set up reminders or brief your cleaner.
        </p>
        <div className={styles.scheduleList}>
          {MAINTENANCE_TASKS.map((item, i) => (
            <div
              key={item.task}
              className={styles.scheduleRow}
              style={{ animationDelay: `${i * 0.04}s` }}
            >
              <span className={styles.scheduleIcon}>{item.icon}</span>
              <span className={styles.scheduleTask}>{item.task}</span>
              <span
                className={styles.scheduleFreq}
                style={{
                  background: FREQ_BG[item.freq],
                  color: FREQ_COLORS[item.freq],
                }}
              >
                {item.freq}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Tips banner */}
      <div className={styles.tipsBanner}>
        <div className={styles.tipsBannerHeader}>
          <span className={styles.tipsHeaderIcon}>💡</span>
          <p className={styles.tipsHeaderTitle}>
            Tips for keeping your laundry room in good shape
          </p>
        </div>
        <div className={styles.proTipsList}>
          {TIPS.map((tip, i) => (
            <div key={i} className={styles.proTipItem}>
              <div className={styles.proTipDot}>{i + 1}</div>
              <p className={styles.proTipText}>{tip}</p>
            </div>
          ))}
        </div>
      </div>

      {/* FAQ */}
      <div className={styles.faq}>
        <p className={styles.sectionEyebrow}>Got questions?</p>
        <h2 className={styles.sectionTitle}>Frequently asked questions</h2>
        <div className={styles.faqList}>
          {FAQS.map((f, i) => (
            <div key={i} className={styles.faqItem}>
              <button
                className={styles.faqQuestion}
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
              >
                {f.q}
                <span
                  className={`${styles.faqChevron} ${openFaq === i ? styles.faqChevronOpen : ""}`}
                >
                  ▾
                </span>
              </button>
              {openFaq === i && <p className={styles.faqAnswer}>{f.a}</p>}
            </div>
          ))}
        </div>
      </div>

      {/* CTA */}
      <div className={styles.cta}>
        <h2 className={styles.ctaTitle}>
          Let a professional handle the deep clean.
        </h2>
        <p className={styles.ctaText}>
          Our vetted maids clean washing machines, dryers, laundry sinks, and
          every corner of your laundry room to a professional standard — all
          products supplied.
        </p>
        <div className={styles.ctaButtons}>
          <button
            className={styles.ctaPrimary}
            onClick={() => navigate("/maids")}
          >
            Browse Maids
          </button>
          <button
            className={styles.ctaSecondary}
            onClick={() => navigate("/request-a-free-estimate")}
          >
            Get a Free Estimate
          </button>
        </div>
      </div>
    </div>
  );
}
